### ISSUE TITLE
Extrair Informações do Ponto

### ISSUE THREAD

**Issue by EdsonRodrigoBA** [controlid/integracao#4]
Bom dia, aqui na empresa onde trabalho utilizamos o relogio de ponto da ControlID, queria saber como faço pra extrair informação referente ao horario que os funcionarios registram as entrada / saidas, se consigo conectar diretamente no equipamento caso ele tenha conexao a rede e extrair essa informação, e qual dll devo utilizar no meu projeto. C#
apenas importar esse dll  : ftrScanAPI.dll  ?

Da forma que e feito hoje um funcinario extrai as informações para um pendrive e sobe em um outro sistema , queremos fazer isso de forma automatizada utilizando a linguagem de programação c#

**Comment by codsec** [comment]
Olá amigo, alguma solução para essa questão? estou passando pelo mesmo atualmente
